################################################################################
## Script Name: python.yaml 
## Description: ansible tasks to install python3 on deb based os 
## Author: Igor Sadza 
## Created: 2023-05-29 
## Last Modified: 2023-05-29 
## Version: 1.0
#################################################################################

- name: Install Python3
  block:
    - name: check presence
      raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_output 

    - name: install package
      raw: apt-get install -qq -y python3
      when: check_output.rc != 0
