name: 'Neovim'

on: 
  workflow_dispatch:
    inputs:
      ssh_host:
        description: 'SSH host ( ip / dns name )'     
        required: true
      ssh_port:
        description: 'SSH port'
        default: '22'
      ssh_user:
        description: 'SSH user'
        default: 'root'
      ssh_pass:
        description: 'SSH password'
        required: true

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:

    - name: Set up jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq   
        
    - run: |
        export TF_VAR_ssh_host=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.ssh_host' )
        export TF_VAR_ssh_port=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.ssh_port' )
        export TF_VAR_ssh_user=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.ssh_user' )
        export TF_VAR_ssh_pass=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.ssh_pass' )

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
